fix: opening yazi in a fugitive buffer falls back to cwd (#1540)
**Issue:**

When https://github.com/tpope/vim-fugitive is used and yazi is opened in
its buffer, an error occurs because yazi cannot handle the `fugitive://`
URI scheme.

```vim
error: invalid value 'fugitive:///Users/foo/gitrep/lib/lexical/.git//' for '[ENTRIES]...': invalid scheme kind: fugitive
```

**Solution:**

Fall back to using equivalent behavior as with `:Yazi cwd` in this case
to avoid the error.

Closes https://github.com/mikavilpas/yazi.nvim/issues/1538